"""Regression checks for staged and published payload identity (no downloads)."""
from __future__ import annotations

import hashlib
import importlib.util
import json
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch
import zipfile

spec = importlib.util.spec_from_file_location("payload_verify", Path(__file__).with_name("verify_staged_payload.py"))
verify = importlib.util.module_from_spec(spec)
spec.loader.exec_module(verify)


class PayloadTests(unittest.TestCase):
    def test_staged_archives_follow_the_published_volumes(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "vs-mlrt-windows-x64-cu129.zip.001").write_bytes(b"first")
            (root / "vs-mlrt-windows-x64-cu129.zip.002").write_bytes(b"second")
            self.assertEqual(
                [path.name for path in verify.staged_archives("cu129", root)[0]],
                ["vs-mlrt-windows-x64-cu129.zip.001", "vs-mlrt-windows-x64-cu129.zip.002"],
            )
            (root / "vs-mlrt-windows-x64-generic.zip").write_bytes(b"whole")
            self.assertEqual(
                [path.name for path in verify.staged_archives("generic", root)[0]],
                ["vs-mlrt-windows-x64-generic.zip"],
            )

    def test_installed_bytes_and_intentional_openvino_layout(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            archive = root / "generic.zip"
            with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as out:
                out.writestr("vsmlrt/manifest.vs", "old manifest, deliberately regenerated by hook")
                out.writestr("vsmlrt/vsncnn.dll", b"new ncnn plugin")
                out.writestr("vsmlrt/vsov/openvino.dll", b"runtime bytes")
            installed = root / "site/vapoursynth/plugins/vsmlrt"
            installed.mkdir(parents=True)
            (installed / "manifest.vs").write_text("merged manifest")
            (installed / "vsncnn.dll").write_bytes(b"new ncnn plugin")
            (installed / "openvino.dll").write_bytes(b"runtime bytes")
            self.assertEqual(verify.verify_installed([[archive]], root / "site", "generic"), 2)
            (installed / "vsncnn.dll").write_bytes(b"old ncnn plugin")
            with self.assertRaisesRegex(RuntimeError, "differs from staged"):
                verify.verify_installed([[archive]], root / "site", "generic")

    def test_missing_installed_file_fails(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            archive = root / "asset.zip"
            with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as out:
                out.writestr("vsmlrt/vstrt.dll", b"new")
            with self.assertRaisesRegex(RuntimeError, "differs from staged"):
                verify.verify_installed([[archive]], root / "site", "generic")

    def test_store_mode_asset_is_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            archive = root / "asset.zip"
            with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_STORED) as out:
                out.writestr("vsmlrt/vstrt.dll", b"payload" * 1024)
            with self.assertRaisesRegex(RuntimeError, "stored uncompressed"):
                verify.verify_installed([[archive]], root / "site", "generic")

    def test_tiny_stored_metadata_is_tolerated(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            archive = root / "vs-mlrt-windows-x64-generic.zip"
            with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as out:
                out.writestr("vsmlrt/vsncnn.dll", b"plugin" * 1024)
            with zipfile.ZipFile(archive, "a", compression=zipfile.ZIP_STORED) as out:
                out.writestr("vsmlrt/manifest.vs", b"[VapourSynth Manifest V1]\nvsncnn\n")
            installed = root / "site/vapoursynth/plugins/vsmlrt"
            installed.mkdir(parents=True)
            (installed / "vsncnn.dll").write_bytes(b"plugin" * 1024)
            self.assertEqual(verify.verify_installed([[archive]], root / "site", "generic"), 1)

    def test_builder_payload_requires_builder_resource(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            archive = root / "vs-mlrt-windows-x64-tensorrt-builder-cu121.zip"
            with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as out:
                out.writestr("vsmlrt/vsmlrt-cuda/trtexec.exe", b"builder")
            installed = root / "site/vapoursynth/plugins/vsmlrt/vsmlrt-cuda"
            installed.mkdir(parents=True)
            (installed / "trtexec.exe").write_bytes(b"builder")
            with self.assertRaisesRegex(RuntimeError, "builder resources"):
                verify.verify_installed([[archive]], root / "site", "cu121")

    def test_publication_requires_tested_payload_digest(self):
        with tempfile.TemporaryDirectory() as tmp:
            evidence = Path(tmp) / "evidence.json"
            wanted = hashlib.sha256(b"tested").hexdigest()
            evidence.write_text(json.dumps({"ok": True, "variant": "cu121", "staged_assets": [{"name": "native.zip", "sha256": wanted}]}))
            with patch.object(verify, "release", return_value={"assets": [{"name": "native.zip", "digest": "sha256:" + wanted}]}):
                verify.verify_published("owner/repo", "cu121", evidence)
            with patch.object(verify, "release", return_value={"assets": [{"name": "native.zip", "digest": "sha256:stale"}]}):
                with self.assertRaisesRegex(RuntimeError, "does not match tested"):
                    verify.verify_published("owner/repo", "cu121", evidence)
            with self.assertRaisesRegex(RuntimeError, "matching staged"):
                verify.verify_published("owner/repo", "cu129", evidence)

    def test_failed_smoke_cannot_authorize_publication(self):
        with tempfile.TemporaryDirectory() as tmp:
            evidence = Path(tmp) / "evidence.json"
            evidence.write_text(json.dumps({"ok": False, "variant": "generic"}))
            with self.assertRaisesRegex(RuntimeError, "requires successful"):
                verify.verify_published("owner/repo", "generic", evidence)


if __name__ == "__main__":
    unittest.main()
